[package]
name = "aoc-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
clap = { version = "4.5.53", features = ["derive"] }
color-eyre = "0.6.5"
indexmap = "2.12.1"
itertools = "0.14.0"
petgraph = "0.8.3"
rangemap = "1.7.0"
